### ISSUE TITLE
Adding the delay distribution to simulated data improves MSE, but on real data it makes it worse

### ISSUE THREAD

**Issue by gcgibson** [gcgibson/ssm_reporting_delay#5]
Data: province-biweek_with_delays.csv

Train: All n_t_ds such that t < 2016-01 , completely filled in rectangle 

Test: n_t_ds from 2016-01 to 2016-01 + D to generate the triangle 

Example when D=5
     
2014-01      - - - - -
2014-02     - - - - -
....

2015-26       - - - - -

2016-01    -  -  -  - 
2016-02    -  -  -
2016-03    -  -  
2016-04    -
MSE is computed on the N_t_infinity predictions for 2016-01 through 2016-0D

**Comment by gcgibson** [comment]
I think this may be related to what @nick was saying about how things get messy if you include all provinces (which I was doing without thinking about it)

**Comment by nickreich** [comment]
Is it documented somewhere what data is being evaluated and how? What exactly are you computing the MSE of? What training data are you using?

**Comment by gcgibson** [comment]
Updated issue with example of train/test, note that for D >= 6 this is not true, the delay distribution improves predictions

**Comment by nickreich** [comment]
In the real data example, D should likely be something like 32 because it can take that long for cases to be reported (i.e. cases are not fully reported until mid-April of year X, so some case counts from January of year X-1 will have a lag of ~32 biweeks). Although maybe we should check the actual data to see what the maximum observed lag is?

Is the simulation mentioned in the title of the issue written up somewhere? 

Also, you say above "for D >= 6 ... the delay distribution improves predictions". Predictions of what? I.e. what timepoints are you evaluating for? This is I think one of the key questions here, and related to lab meeting today: 
 - what are the timezeroes and dataversiondates?
 - what targets are you forecasting for each timezero? 

I'm imagining a setting where the timezeroes are (per diagram at top comment):
 - 2016-01, 2016-02, 2016-03, ..., 2016-26, 2017-01, ..., 2017-26

The data-version-dates (each corresponding to the timezeroes, in order):
 - 2016-06, 2016-07, 2016-08, ..., 2016-26, 2017-01, ..., 2017-26, 2018-01, ..., 2018-05

And the targets are, say, k-biweek-ahead forecasts for k \in {1, 2, ..., 8}

**Comment by gcgibson** [comment]
Thanks for the comment! 

1) yeah the code is in this repo under simple_delay.py

2) I'm not totally clear on data version date but it seems like it is timezero +D? If so you're description above seems correct. I'm just confused because it's unclear if data version date refers to complete or incomplete data or both. 


3) I don't think targets mater when comparing models? We are evaluating p(Data |Model with delay) / p(Data | Model without delay) . So your question above is a good one but it doesn't affect model comparison as long as we keep Data the same for both models.

**Comment by gcgibson** [comment]
Sorry that last line should read as long as we keep the data and targets the same when comparing two models.

**Comment by nickreich** [comment]
I don't see data-version-date as being tied to D. 

D is the maximum possible lags that we can observe in our data. it is fixed by the data generation process by, in our case, the Thai MOPH. In our case it needs to be something like 32, because that is how long it takes for some cases to be reported.

data-version-dates refer to dates to which we are hypothetically turning back the clock to run an analysis. E.g. We might have a data-version-date of 2016-BW06 which means that we can only use data available "at that time" (say, e.g. the first day of BW06).

**Comment by nickreich** [comment]
Also, I don't understand what you mean about targets not mattering when comparing models. we want to make an evaluation of f_m(z|data), the predictive density from model m for target z given our data. that is the primary outcome of interest. and we might want this for a set of z's.

**Comment by gcgibson** [comment]
But we don't care what the targets are...only that we get the likelihood of the target under each model and take the ratio or whatever we want to do. As long as they are the same it doesn't mater what they are

**Comment by gcgibson** [comment]
okay, I think I'm starting to understand the data version date....in our case we are turning back the clock to 2016-01-01 and I think that is also our t zero, and we are evaluating from that point forward ? Is that the idea?

**Comment by gcgibson** [comment]
I retract my comment about targets not mattering. The delay distribution might help on some targets and hurt on others so we might want to condition on z like you are suggesting

**Comment by nickreich** [comment]
The data-version-date stuff is really confusing to me. The time to which we turn back the clock and the timezero are different concepts. see overleaf writeup...

**Comment by gcgibson** [comment]
Notation is mostly cleared up....please refer to https://github.com/gcgibson/ssm_reporting_delay/blob/master/delay.ipynb
